
platform:
  - x64

environment:

  matrix:
  - BUILD: Qt4.8.6-x86-mingw482-4.8.7

    QTMOVE: '$OUTDIR\bin 4.8.7-x86-mingw482-4.8.7'
    QTSUB: '4.8.6-x86-mingw482-4.8.7'

    QTDOWNLOAD1: http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-mingw482-4.8.7.exe
    QTARCHIVE1: 'qt-opensource-windows-x86-mingw482-4.8.7.exe'
    QTARCHIVE1_OPTS: '"-ir!?OUTDIR\*" "-xr!*doc\*" "-xr!*examples\*" "-xr!*demos\*"'

install:

  - path

  # fix git\bin bug for cmake mingw generator
  - set "PATH=%PATH:Git\bin;=Git\cmd;%"

  # prepare Qt install
  - choco install -y curl 7zip

  # install Qt
  - mkdir Qt
  - cd Qt

  # download and extract
  #- if defined QTDOWNLOAD1 curl -kLO %QTDOWNLOAD1%
  - curl -kLO  http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-mingw482-4.8.7.exe
  #- if defined QTARCHIVE1 7z x %QTARCHIVE1_OPTS% %QTARCHIVE1% >nul
  # quiet extract
  - 7z x qt-opensource-windows-x86-mingw482-4.8.7.exe > nul

  # move to payload
  #- if defined QTMOVE move %QTMOVE%
  - dir
  # funny dir name inside appveyor, should be $OUTDIR
  - move $_14_ Qt-4.8.7
  - dir
  - cd Qt-4.8.7
  - dir
  - cd ..
  #- if defined QTSUB set "QTDIR=%CD%\%QTSUB%"
  - set QTDIR=%CD%\Qt-4.8.7
  - echo %QTDIR%
  - echo [Paths]   >  %QTDIR%\bin\qt.conf
  - echo Prefix=.. >> %QTDIR%\bin\qt.conf
  - type %QTDIR%\bin\qt.conf
  - cd ..


  # finish install
  - set "PATH=%QTDIR%\bin;%PATH%"
  - path
  - dir
  - qmake --version

  # puth Mingw 4.8.2 on the path
  # Add MinGW to path
  - path  C:\MinGW\bin;%PATH%
  - g++ --version
  - flex --version
  - bison --version
  
  #- git clone https://github.com/Qucs/qucs.git qucs-clone
  
  # Build Qucs-GUI
  #- cd qucs-clone
  #- cd qucs
  #- mkdir cmake_build
  #- cd cmake_build
  #- cmake .. -G "MinGW Makefiles"
  #- mingw32-make
  #- cd ..
  #- cd ..
  
  # Build ADMS
  # - amds 2.3.4 requires Bison 2.6, 
  # - adms-master builds fine with 2.4, using master for the moment...
  
  # Get strawberryperl to bootstrap ADMS (need XML:LibXML already included)
  - cinst -y strawberryperl
  - path C:\Strawberry\perl\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\c\bin;%PATH%
  
  #- curl -kLO http://sourceforge.net/projects/mot-adms/files/adms-source/2.3/adms-2.3.4.tar.gz
  #- 7z x adms-2.3.4.tar.gz > nul
  #- 7z x adms-2.3.4.tar
  #- cd adms-2.3.4
  
  - git clone https://github.com/Qucs/ADMS.git adms-master
  - cd adms-master
  
  - mkdir cmake_build
  - cd cmake_build
  #- cmake .. -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX="C:\projects\test-appveyor\local\adms"
  - cmake .. -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX="C:\projects\test-appveyor\local\adms" -DUSE_MAINTAINER_MODE=ON
  - mingw32-make install
  - cd ..
  - cd ..
  - path C:\projects\test-appveyor\local\adms\bin;%PATH%
  - admsXml -h
  
  # Build Qucs-core
  #- cd qucs-clone
build_script:
  - dir
