# version format
version: 1.0.{build}

# version: 1.0.{build}-{branch}

os: MinGW

build:
  verbosity: minimal


# scripts that run after cloning repository
install:
 - perl -V
 - 'echo Starting install at: & time /t'

# Install Strawberry Perl from Chocolatey
 - cinst -y strawberryperl
 - path
 - path C:\Strawberry\perl\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\c\bin;%PATH%
 - perl -V
 #- cpan XML::LibXML  # need to get LibXML?
 - 'echo End intall at: & time /t'

 - echo %cd%
 - git clone https://github.com/Qucs/ADMS.git adms
 - cd adms
 - mkdir cmake_build
 - cd cmake_build
 - cmake .. -DUSE_MAINTAINER_MODE=ON -DCMAKE_VERBOSE_MAKEFILE=ON -G'MinGW Makefiles'
 - make


