# version format
version: 1.0.{build}

# version: 1.0.{build}-{branch}

os: MinGW

build:
  verbosity: minimal


# scripts that run after cloning repository
install:
  - choco install -y mingw-get
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
  #- mingw-get install mingw-developer-toolkit
  #- mingw-get install msys-zip
  #- mingw-get install msys-unzip
  - mingw-get install autotools autoconf automake

  - g++ --version
  - flex --version
  - bison --version


  - echo %cd%
  - git clone https://github.com/Qucs/ADMS.git adms
  - cd adms
  - C:\MinGW\msys\1.0\bin\sh --login -c "
      echo 'C:\MinGW\ /MinGW' > /etc/fstab;
      cd /c/projects/test-appveyor/adms;
      mkdir cmake_build;
      cd cmake_build;
      cmake .. -DUSE_MAINTAINER_MODE=ON -DCMAKE_VERBOSE_MAKEFILE=ON -G'MSYS Makefiles';
      make;
      "
