platform:
  - x64
environment:
  global:
    MSYS2_BASEVER: 20150512
  matrix:
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
#    - MSYS2_ARCH: i686
#      MSYSTEM: MINGW32
#      MSYS2_BITS: 32
install:
  - appveyor DownloadFile "http://kent.dl.sourceforge.net/project/msys2/Base/%MSYS2_ARCH%/msys2-base-%MSYS2_ARCH%-%MSYS2_BASEVER%.tar.xz" -FileName "msys2.tar.xz"
  - 7z x msys2.tar.xz
  - 7z x msys2.tar > NUL
  - msys64\msys2_shell.bat
  - pacman -Sy
  - pacman --needed --noconfirm -Sy bash pacman pacman-mirrors msys2-runtime
  - exit
  - msys64\msys2_shell.bat
  - pacman -Su
  #- msys64\usr\bin\bash -lc "pacman --noconfirm -Suy mingw-w64-x86_64-toolchain"
  #- msys64\usr\bin\bash -lc "pacman --noconfirm -Suy automake autoconf libtool m4 make flex bison"
  #- msys64\usr\bin\bash -lc "pacman --noconfirm -Suy perl perl-XML-LibXML"
  #- flex --version
  #-
build_script:
  - cd $APPVEYOR_BUILD_FOLDER
  - dir 
